CREATE TABLE Tasks (
    TaskId SERIAL PRIMARY KEY,
    TaskTitle varchar(60) NOT NULL,
    TaskDescription varchar(255) DEFAULT NULL,
    DueDate TIMESTAMP DEFAULT NULL,
    UserId INTEGER REFERENCES Users(id) ON DELETE CASCADE NOT NULL,
    EnterDate TIMESTAMP DEFAULT now() NOT NULL
);